### ISSUE TITLE
在美国突然不能看番了

### ISSUE THREAD

**Issue by fireattack** [bilibili-helper/bilibili-helper#240]
http://www.bilibili.com/video/av5651936/

不会提示视频不存在，但是加载一下就刷新到“非常抱歉”

**Comment by zacyu** [comment]
Verified. It seems that bilibili doesn't honor X-Forward-For or Client-IP header any more. I will take a deeper once I have time.

**Comment by happlebao** [comment]
变成只能看广告了。。。

**Comment by feidouer** [comment]
我在澳洲，也是不能看新番了，进去之后加载小电视然后一闪刷新之后就变成“非常抱歉”那个33娘音频了

**Comment by blackcatciao** [comment]
墨尔本这也不行，_(:3 」∠)_

**Comment by Bakuluckly** [comment]
日本这边也是不行QWQ

**Comment by euraka** [comment]
欧洲同样不行，希望早日有解决方法。好多点没能看番了

**Comment by steven7851** [comment]
海外只能先搭着[Unblock Youku](https://github.com/uku/Unblock-Youku)看新番了，希望早日修复(´;ω;`)

**Comment by Suzixuan** [comment]
08/13 问题同上

**Comment by HuJeanLuc** [comment]
16/08/16 （欧洲），同上，新番看不了，之前还能用Unblock Youku看看的，但现在都不行了O__O "…，希望能早点有办法看得到，还有辛苦你了↖(^ω^)↗加油

**Comment by jjj201200** [comment]
该功能下个版本会重新添加到助手中
