### ISSUE TITLE
可以为Edge浏览器做一个么

### ISSUE THREAD

**Issue by KnightBlood** [bilibili-helper/bilibili-helper#377]
请问 官方有为edge 浏览器 做了对应修改的哔哩哔哩助手么？
我fork了代码 尝试利用微软提供的 chrome插件转置edge插件 的工具进行了转置 虽然成功了 但是让然存在一些问题 我希望官方能够为edge做一个

**Comment by jjj201200** [comment]
我们希望可以在各个平台的商店正式上架，而非仅仅开发在github里提供下载。救我之间了解的似乎edge比较难的样子。不过会争取的

**Comment by yym0924** [comment]
@jjj201200 请问对Edge的支持计划还在进行吗？因为目前Edge渐渐完善，所以使用起来还报错，希望哔哩哔哩助手也可以被带到Edge上

**Comment by jjj201200** [comment]
@yym0924 我们正在为此努力，不久之后就有新进展。
