### ISSUE TITLE
希望能出一个火狐浏览器的版本

### ISSUE THREAD

**Issue by Spturate** [bilibili-helper/bilibili-helper#494]
希望能出一个火狐浏览器的版本

**Comment by SUtong95** [comment]
有过，不过现在好像下架了！火狐扩展商店搜不到了！

**Comment by thanksshu** [comment]
同感啊，需要火狐插件。

**Comment by mycraftmw** [comment]
同上！

**Comment by ShadyWhite** [comment]
同上！0.9.9以及之前的版本还可以通过一键转换在火狐浏览器上运行，1.1.1以及之后的就不行了，难受_(:з」∠)_

**Comment by doio** [comment]
转换的时候好像 5-6 个 JS 错误，_(:з」∠)_
用也用不了，而且也下架了，(╥╯^╰╥)

**Comment by eebssk1** [comment]
emmm所以火狐版和chrome版的更新信息能不能分开查询啊,每次打开设置页都显示有新版,然而火狐版的并没有出....

**Comment by jjj201200** [comment]
请各位再等待一下

**Comment by C7C7** [comment]
chrome更新了，我最爱的FF都下架了T-T

**Comment by jjj201200** [comment]
请各位再等一段时间，chrome上的版本还有诸多问题，再过几个版本等问题基本没有我自然会上传到ff上的好吗，再耐心等几个版本

**Comment by C7C7** [comment]
> 请各位再等一段时间，chrome上的版本还有诸多问题，再过几个版本等问题基本没有我自然会上传到ff上的好吗，再耐心等几个版本

感谢您的辛勤付出

**Comment by eebssk1** [comment]
请问火狐版本出了吗

**Comment by eebssk1** [comment]
还没更新啊。。。遗弃火狐支持了吗..

**Comment by jjj201200** [comment]
更了哈
