### ISSUE TITLE
【功能请求】增加HTML5播放器的触屏支持

### ISSUE THREAD

**Issue by JeffGe05** [bilibili-helper/bilibili-helper#548]
目前我正在使用 Surface 和 Chrome 浏览器访问 B 站，但是 Surface 的触屏操作在 HTML5 播放器上仍然使用的是鼠标点击的逻辑，操作十分不便。插件能否增加一个选项打开“触屏模式”，打开后操作逻辑更改为适合触屏操作的方法，例如：
* 单击：显示/隐藏菜单栏和标题栏
* 双击：播放/暂停
* 向左/向右滑动：前进/后退
* 向上/向下滑动：音量加/减

B 站反馈区已经有人提出相同的建议了，但是目前没有后续消息。http://link.acg.tv/forum.php?mod=viewthread&tid=17615
我在一个油猴脚本内看到了一个触屏功能的实现，但是我实际用了一下似乎滑动操作都不能正常使用。https://github.com/the1812/Bilibili-Evolved
谢谢！

**Comment by jjj201200** [comment]
你好，目前我觉得该功能被添加到助手中的可能性不大。
因为我目前我手头并没有类似surface这样的触摸屏电脑，难以进行调试呢，非常抱歉。
如果有可能的话，会和快捷键功能一同上架。

**Comment by JeffGe05** [comment]
是的，除了调亮度吧，我想 Chrome 可能没有提供调节屏幕亮度的接口或权限。

**Comment by jjj201200** [comment]
该请求已经被添加到官网投票区。
