### ISSUE TITLE
1.2.0版本预告

### ISSUE THREAD

**Issue by jjj201200** [bilibili-helper/bilibili-helper#549]
本文用于预报和展示一些会在1.2.0版本中更新的内容。

具体如下：
1. 调整主站助手按钮移动到屏幕右侧边缘'试用反馈'按钮处；
4. 调整**最近推送列表**功能中推送数量上限至100；
1. 修复 **字幕下载** 功能失效的问题；
5. 修复新版番剧页面助手无法显示的问题 #553；
4. 优化 **自动签到**、**银瓜子兑换硬币** 和 **更新检测** 功能在时区转换问题；
4. 优化 **字幕下载** 功能的显示逻辑，现在没有字幕时不会显示该模块；
4. 优化**画中画**功能的逻辑，现在手动切视频时会自动替换已经打开的画中画窗口视频；
4. 优化**弹幕查询**功能中弹幕列表的显示，现在不会出现因为需要加载大量弹幕而导致页面卡顿的问题；
3. 增加 **跨区域解锁** 功能 #240；
5. 增加可以下载到分段flv文件与 **合并后的文件** 的功能 #385，并且现在默认隐藏flv分段下载按钮，需要显示分段的话，可在设置页面中开启“显示FLV分段”选项；
2. 增加新功能 **版聊模式**，开启后该功能在直播间进入网页全屏时会屏蔽弹幕并将右侧聊天内容显示在播放器上；
5. 增加**夜间模式**功能，仅在主站新版视频播放页面中生效；
5. 新的动态推送功能，现在可以选择4种类型的推送内容（视频投稿，小视频，专栏，番剧）；
5. 更新投喂信息。

**Comment by jjj201200** [comment]
下个版本开始将严格遵守语义化版本号命名规则: [https://semver.org/](https://semver.org/)。

其中关于测试版本号的约定：
在扩展中使用第四位数字（x.x.x.x）作为测试版本号。
在文件命名时使用x.x.x-beta.x这样的方式进行命名。

**Comment by feelthesea** [comment]
请问1.2.0版本什么时候更新？已经一个月无法下载视频了。

辛苦啦！！给大佬泡茶！

**Comment by jjj201200** [comment]
@feelthesea 已经增加了，我会在测试群先发布测试版，再等一段时间后上架。

**Comment by feelthesea** [comment]
> @feelthesea 已经增加了，我会在测试群先发布测试版，再等一段时间后上架。

求进测试群哇！

**Comment by LYY** [comment]
这个版本会上架firefox吗？

**Comment by jjj201200** [comment]
@LYY 这个版本我不确定，但是可以确定的是一定在chrome上线之后
何时在google应用商店上架，这里可以告知的是，我们正在尝试解决新页面mp4下载问题，但目前并没有很好的结果。

**Comment by LYY** [comment]
@jjj201200 希望能有好消息，在mac上chrome的播放很差，弹幕稍多就会卡顿，现在已经主用Firefox来上B站了。
