### ISSUE TITLE
【功能请求】希望增加专栏cv查看原图/下载原图/批量下载原图功能

### ISSUE THREAD

**Issue by hv0905** [bilibili-helper/bilibili-helper#551]
## 问题反馈
如题,b站专栏图片的下载保存实在是太麻烦了,直接保存保存下来的是webp格式的,还得改url才能拿到原图
希望在专栏加入这些功能
1. 点击查看原图/下载原图
2. 在右侧加入批量下载原图按钮

[可以参考一下我之前写的油猴脚本](https://github.com/hv0905/bilibiliCv_downloader) (乱写的勿喷=.=)

以上.ありがとう

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):Windows Chrome
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):71.0.3578.80
3. 扩展版本:1.1.8

**Comment by jjj201200** [comment]
你好，想请问一下既然有油猴脚本为何要希望助手添加该功能呢？

助手目前主要针对主站视频和直播区进行功能的维护，其他方面的功能暂时并没有考虑加入呢。还望理解~

**Comment by jjj201200** [comment]
emmmm，但是你如果愿意的话，可以根据助手目前的框架编写并提交pr，我会检查后进行合并。
但是要求该功能默认是关闭的，需要用户手动开启。

**Comment by jjj201200** [comment]
已经在1.2.1中添加
