### ISSUE TITLE
哔哩哔哩助手的菜单经常消失

### ISSUE THREAD

**Issue by Helly0000** [bilibili-helper/bilibili-helper#552]
### 环境信息
1. 操作系统  Windows 10
2. 浏览器版本Chrome最新版：版本 71.0.3578.98（正式版本） （64 位）
3. 扩展版本 最新版1.1.8

### 重现步骤/尝试的解决方案
哔哩哔哩助手的菜单经常消失或者被充电按钮挡住。页面在加载的时候还有，但是加载完了却不见了。
![2](https://user-images.githubusercontent.com/35934370/50961248-2d8f6180-1502-11e9-81ef-f4cab7503ec3.JPG)
![default](https://user-images.githubusercontent.com/35934370/50961263-341dd900-1502-11e9-8c09-901c76b7a09c.JPG)

重装插件可以恢复，但是打开几个页面之后又会消失。

**Comment by starxjys** [comment]
好像只有在网页加载慢的情况下才会出现

**Comment by jjj201200** [comment]
这个问题只怕是只能讲按钮放到别的地方才能解决了。尤其是网页加载慢的时候尤为突出。

**Comment by Helly0000** [comment]
> 这个问题只怕是只能讲按钮放到别的地方才能解决了。尤其是网页加载慢的时候尤为突出。

大佬对B站新版UI启用插件有什么计划吗？

**Comment by xmcp** [comment]
不如直接把功能放在browser action里？毕竟这样无论如何都不会跟B站页面冲突（笑）

**Comment by jjj201200** [comment]
@xmcp 非全局的功能优先考虑页面注入，不然都往里头放会很重，pakku就不需要这个考虑

**Comment by xmcp** [comment]
@jjj201200 本来chrome扩展的page action就是用于显示页面相关的功能的，只是现在chrome把page action和browser action合并成一个图标了。我的想法是如果可行的话，把视频相关的UI用模块的形式放进browser action弹窗。（不过这样确实有些麻烦）

**Comment by jjj201200** [comment]
@xmcp 先不说他本来的初衷是什么，在浏览页面时注意力应该是在页面正文才对呀。这也是我为什么就算把按钮放页面边缘也不太情愿的原因。主要还是习惯问题。当用户在浏览页面的时候不应该主动让他跳出页面而是尽可能平滑的过渡切换页面或者显示UI

**Comment by xmcp** [comment]
@jjj201200 我说的是实现可能有些麻烦，比如弹窗页面的布局大概要改。emm 好像你说的也是一个问题

**Comment by jjj201200** [comment]
@xmcp 还好还好，例如怎么把音视频流合并的问题倒确实挺麻烦的

**Comment by jjj201200** [comment]
1.2.0+版本开始助手将在新播放页面中将助手移动至新旧页面切换按钮附近。
