### ISSUE TITLE
好多视频都下不下来了。用的就是旧版

### ISSUE THREAD

**Issue by cottonty** [bilibili-helper/bilibili-helper#553]
全都显示未支持的视频数据

举几个例子
1. 这里的全部视频：https://www.bilibili.com/video/av33140233/
2. https://www.bilibili.com/video/av23108121
3. https://www.bilibili.com/video/av36579213
4. https://www.bilibili.com/video/av38389296

**Comment by pethrowilo** [comment]
流展示方式变了, 应该是全部无法下载了吧

**Comment by cottonty** [comment]
> 流展示方式变了, 应该是全部无法下载了吧

也不是，还有好多能下的。不会是我浏览器缓存吧[facepalm

**Comment by jjj201200** [comment]
谢谢反馈，该问题确实存在，老版页面也开始替换新的视频数据格式了
