### ISSUE TITLE
【功能请求】希望能增加多账号签到功能

### ISSUE THREAD

**Issue by Mr-Haotian** [bilibili-helper/bilibili-helper#556]
## 需求反馈

希望可以新增多账号的签到功能来实现多个B站账号能自动签到,自动领瓜子,可以吗?

### 环境信息

1. 操作系统 (Windows/macOS/Linux):**macOS版本10.13.6**
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):**Chrome版本 71.0.3578.98（正式版本） （64 位）**
3. 扩展版本:**BILIBILI HELPER version 1.1.8（正式版）**

**Comment by jjj201200** [comment]
该请求已经被添加到官网投票区。
