### ISSUE TITLE
请求dark mode……

### ISSUE THREAD

**Issue by asanokiyoe** [bilibili-helper/bilibili-helper#558]

**Comment by jjj201200** [comment]
很不错的提议，能描述一下你的具体需求你的想法吗。

**Comment by asanokiyoe** [comment]
因为个人比较喜欢灰暗背景色所以想要dark mode🙇‍
主要是希望视频观看页面能设置成黑暗模式，B站全局倒不一定都要弄成黑色背景
具体例子的话，Improve YouTube!这个插件里的night mode是我非常喜欢的效果

**Comment by jjj201200** [comment]
@asanokiyoe 啊哈，去体验了一把，确实不错。我会参考着加上去的，敬请期待。

**Comment by jjj201200** [comment]
@asanokiyoe b站有关灯模式可否知道？可以试试

**Comment by asanokiyoe** [comment]
> @asanokiyoe b站有关灯模式可否知道？可以试试

说的是右键的那个关灯么？之前有用过，不过那个把周围都变暗了，其实有时候想下拉看看评论或者别的就不太方便，我是希望那一整个视频观看页面都有dark mode，视频简介/评论那些文字可以反白显示。其他的首页/消息/历史记录/收藏夹etc就不强求，B站各种页面比较多，全局设置起来应该也挺繁琐吧，不过还是很期待用上类似那个YTB插件的效果的哈哈
感谢回复，如果能添加这个功能就太好了🙇‍

**Comment by jjj201200** [comment]
@asanokiyoe b站的蓝色和粉色并不适合做夜间模式呢，但是我试了一下，你可以去群里下载测试版本进行试用，应该还有要调整的地方

**Comment by jjj201200** [comment]
你好，我发现youtube自带有深色背景主题，并不需要你提到的那款插件
![image](https://user-images.githubusercontent.com/3397549/52902705-7cda5780-324f-11e9-8389-a227a33f79d3.png)
