### ISSUE TITLE
【功能请求】关闭小视频动态自动播放

### ISSUE THREAD

**Issue by Vixb1122** [bilibili-helper/bilibili-helper#561]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): Windows
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Cent 3.8.5.69
3. 扩展版本: 1.1.8

现在动态里面的小视频动态默认是自动播放的，而且无法找到开关。希望可以提供该功能！

**Comment by jjj201200** [comment]
该请求已经被添加到官网。
