### ISSUE TITLE
该扩展更改了网站字体

### ISSUE THREAD

**Issue by sickneet** [bilibili-helper/bilibili-helper#562]
版本 1.18正式版
除了番剧区的视频之外，扩展更改了其它所有的视频网页的字体
有的字体是被加粗了，有的是被模糊化了，有的是加粗之后模糊化了
我使用F12审查元素删除了中间的视频，便于截图观看

番剧区视频的正常情况
![image](https://user-images.githubusercontent.com/30150112/53866066-9e975500-402b-11e9-8608-54f011dc70b6.png)
其它视频页面的不正常情况
![image](https://user-images.githubusercontent.com/30150112/53866186-eddd8580-402b-11e9-9865-ba8c7c75416b.png)
该页面正常情况下是这样的
![image](https://user-images.githubusercontent.com/30150112/53866731-334e8280-402d-11e9-9dc6-d70e0a141c00.png)

希望尽快修复！

**Comment by jjj201200** [comment]
你好，助手并没有进行相关的更改。请将你的安装的助手关闭后确认问题是否依旧存在来进行问题的排除。并再请确认浏览器是否安装有其他样式扩展修改了样式，或者其他任何可能造成这种影响的软件。

**Comment by AnnAngela** [comment]
建议右键被更改样式的元素，检查CSS表，看是哪个文件修改的，就知道是谁改的

**Comment by sickneet** [comment]
> 你好，助手并没有进行相关的更改。请将你的安装的助手关闭后确认问题是否依旧存在来进行问题的排除。并再请确认浏览器是否安装有其他样式扩展修改了样式，或者其他任何可能造成这种影响的软件。

我关闭这个助手之后就正常了，所以我说是这个扩展改的。

**Comment by jjj201200** [comment]
@sickneet 感谢您提出的问题，经过仔细排查确实存在全局覆盖字体和字号的问题，即将上架的新版本中将不会再出现这个问题了。
