### ISSUE TITLE
视频下载文件名不正确

### ISSUE THREAD

**Issue by qiyulan** [bilibili-helper/bilibili-helper#564]
### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):
windows
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):
Chrome 72 64bit
3. 扩展版本:
1.2.0
您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
视频下载文件名及扩展名不正确  
点击右侧的视频下载 等待下载结束 弹出的下载保存框中名字为 UUID.txt 而非 视频名称.flv
![image](https://user-images.githubusercontent.com/17901676/54080285-60e64500-4327-11e9-9f0e-af2702e7642e.png)

**Comment by jjj201200** [comment]
请问所有视频下载都有这个问题还是就单个视频是有问题的？可否发一下出问题的视频地址，谢谢

**Comment by qiyulan** [comment]
试了十几个链接都有这个问题  
例如  
https://www.bilibili.com/video/av45844876/  
https://www.bilibili.com/video/av45836940/

**Comment by jjj201200** [comment]
请问您是否还启用了其他扩展程序或者插件脚本呢？

**Comment by jjj201200** [comment]
请尝试如下操作，另存为txt后的文件大小是否正常，如果很小，尝试打开这个文件，查看其中内容是什么。如果文件大小差不多是一个视频的大小，尝试修改器后缀为flv，并用播放器打开，确认是否可以正常打开。

**Comment by qiyulan** [comment]
文件大小为视频大小,可以使用播放器播放,只是文件名错误  
目前不能判断是否是其他扩展干扰,在纯净的用户下安装本扩展无法识别视频,提示更换清晰度来下载

**Comment by jjj201200** [comment]
“在纯净的用户下安装本扩展无法识别视频”，请问“在纯净的用户下安装”指的是？
另外还请您通过关闭其他全部的扩展程序来帮助我们排除问题，确认是否助手的问题好吗？因为我们目前无法复现你碰到的问题。

**Comment by ma0575** [comment]
> “在纯净的用户下安装本扩展无法识别视频”，请问“在纯净的用户下安装”指的是？
> 另外还请您通过关闭其他全部的扩展程序来帮助我们排除问题，确认是否助手的问题好吗？因为我们目前无法复现你碰到的问题。

你好 我这边遇到类似的问题 排查了下是下面这个扩展程序引入的
https://chrome.google.com/webstore/detail/chrono-download-manager/mciiogijehkdemklbdcbfkefimifhecn
不知道对您解决类似问题有没有帮助

**Comment by jjj201200** [comment]
@ma0575 非常感谢提供的帮助，我将会使用你提供的信息进行问题来源的确认，期望最终能够确定并找到比较好的解决方案。

**Comment by HydrogenDeuterium** [comment]
出现同样问题。
windows10 
chrome74.0
软件版本1.2.1
同时出现下载错误，我在下载
https://www.bilibili.com/video/av54554866
对应的视频情况下，经过检查实际下载的视频是
https://www.bilibili.com/video/av51570724

**Comment by jjj201200** [comment]
请排查是否安装有chrome下载管理插件，该插件会控制浏览器下载管理权限并做修改。

**Comment by yidasanqian** [comment]
同样的问题，版本1.2.1，安装有chrome [aria2-manager](https://chrome.google.com/webstore/detail/aria2-manager/lbfekjdfefiipnbkpgldhicajcoldcmb)

是否可以提供导出到aria2下载？

**Comment by jjj201200** [comment]
@yidasanqian 和aria相关请另外再开一个issue谢啦~
不过目前应该支持不了，目前能够下载的是仅限于在b站页面发送的源的下载请求，希望之后可以找到更好的方法

**Comment by jjj201200** [comment]
@novolife 请问可够加一下q群，我改了个版本，可以帮忙测一下吗，我复现不了这个问题

**Comment by novolife** [comment]
> @novolife 请问可够加一下q群，我改了个版本，可以帮忙测一下吗，我复现不了这个问题

@jjj201200 测试版那个下载确实没有没有问题了

**Comment by jjj201200** [comment]
fixed in  v1.2.3
