### ISSUE TITLE
视频下方按钮宽度调整

### ISSUE THREAD

**Issue by AnnAngela** [bilibili-helper/bilibili-helper#566]
请保留一种您需要的语言版本的报告模板

## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): Windows 10 Pro Version 1809 (17763.316)
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): 版本 72.0.3626.121（正式版本） （64 位）
3. 扩展版本: 版本 1.2.1.2（正式版）

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
视频下方的按钮宽度被默认样式写死，导致其他同样添加按钮的扩展的按钮会重叠
![image](https://user-images.githubusercontent.com/9762652/54119499-73987100-4430-11e9-97ba-6224c3243dc4.png)
建议新加一条样式`width: auto;`来解决这个问题
![image](https://user-images.githubusercontent.com/9762652/54119561-988ce400-4430-11e9-809d-4d4df6dcd50f.png)

**Comment by jjj201200** [comment]
👌
