### ISSUE TITLE
直播页面出现问题，主站无问题。

### ISSUE THREAD

**Issue by Huiaei** [bilibili-helper/bilibili-helper#567]
### 环境信息
1. 操作系统:Windows 10 64bit
2. 浏览器版本:Chrome 72.0.3626.121（正式版本）（64 位）
3. 扩展版本:1.2.1.3（正式版）

#### 出现问题截图
[![Snipaste_2019-03-12_21-45-49.png](https://i.loli.net/2019/03/12/5c87bb361d71b.png)](https://i.loli.net/2019/03/12/5c87bb361d71b.png)

>上面显示未登录其实是有登陆的。

#### 设置截图
[![Snipaste_2019-03-12_21-44-06.png](https://i.loli.net/2019/03/12/5c87bb352938d.png)](https://i.loli.net/2019/03/12/5c87bb352938d.png)
[![Snipaste_2019-03-12_21-44-17.png](https://i.loli.net/2019/03/12/5c87bb352c707.png)](https://i.loli.net/2019/03/12/5c87bb352c707.png)
[![Snipaste_2019-03-12_21-43-46.png](https://i.loli.net/2019/03/12/5c87bb3530607.png)](https://i.loli.net/2019/03/12/5c87bb3530607.png)
[![Snipaste_2019-03-12_21-43-58.png](https://i.loli.net/2019/03/12/5c87bb3532445.png)](https://i.loli.net/2019/03/12/5c87bb3532445.png)

***
已经排除了其他插件的影响，确定了问题源头的确为此插件。
在主站没有事，但是直播直接全部有问题，账号显示未登录。礼物出错，聊天栏也有问题

**Comment by jjj201200** [comment]
谢谢反馈，该问题我已经在解决了，请下载1.2.1.4测试版本。

**Comment by ChromeHu** [comment]
Hi，感谢你能抽出时间去修复它。
***
我想问一下可不可以在国内网盘中上传？直接下载文件我这边不知道是那边出现的问题，下载时经常容易出错。

**Comment by jjj201200** [comment]
暂时不提供网盘下载呢，太麻烦了

**Comment by ChromeHu** [comment]
从官网下载的beta版，拖进扩展中显示**此扩展程序可能已损坏**。如何处理？

**Comment by ChromeHu** [comment]
已从google 扩展商店重下了1.2.1.8版本，暂时未发现问题

**Comment by jjj201200** [comment]
@ChromeHu 测试版本使用解压缩方法安装，1.2.1.8还没有在商店上架，你怎么下载到的？？？

**Comment by ChromeHu** [comment]
今天又发现了出现了类似问题，显示没有登陆，后面发现貌似是“跨区域解锁”的问题，关闭了就正常了。
***
感觉是弄串了啊。。。不过可以正常使用
[![Snipaste_2019-03-23_20-58-19.png](https://i.loli.net/2019/03/23/5c962d7f34641.png)](https://i.loli.net/2019/03/23/5c962d7f34641.png)
[![Snipaste_2019-03-23_20-58-26.png](https://i.loli.net/2019/03/23/5c962d7fe5275.png)](https://i.loli.net/2019/03/23/5c962d7fe5275.png)

**Comment by wanguaf2016** [comment]
扩展 1.2.1.8 正式版本再次出现这个问题。
浏览器是 Cent Browser 3.9.2.45（正式版本） （64 位） (Chromium 72.0.3626.121)

**Comment by ChromeHu** [comment]
关闭“跨区域解锁”之后未遇到该问题复现。

**Comment by jjj201200** [comment]
诶呀，该issue还不能关闭哈。。毕竟开启后仍旧有人有问题

**Comment by ChromeHu** [comment]
噢，那这个你们能关闭的吧？

**Comment by sola97** [comment]
![image](https://user-images.githubusercontent.com/17388849/55962903-59a6b400-5ca4-11e9-885e-6ed9f4b201a4.png)
跨区域解锁，这个IP在直播界面已经炸了

**Comment by jjj201200** [comment]
@sola97 仅部分用户是这样的，暂时不清楚原因

**Comment by wanguaf2016** [comment]
我这边现在出现的情况是，刚打开直播页面没问题，但过一会之后就发现领瓜子领不了了，发弹幕也发不出去，这时候刷新就会出现页面异常。关闭跨区域后恢复。
操作系统:Windows 10 64bit
浏览器版本:Chrome 72.0.3626.121（正式版本）（64 位）
扩展版本:1.2.1（正式版）

**Comment by xxxxuanran** [comment]
[api.live.bilibili.com/ajax/feed/count](https://api.live.bilibili.com/ajax/feed/count)比较好奇这个接口是做什么用的？试着将 api.live.bilibili.com 重定向至127.0.0.1 且开启插件的区域解锁功能，能够正常播放受限制的番剧/弹幕。不知可否去除对 api.live.bilibili.com 的代理呢？
![TIM截图20190420012603_LI](https://user-images.githubusercontent.com/31968665/56435926-c35e3800-630c-11e9-8678-4476c0d2489a.jpg)

操作系统:Windows 10 1803
浏览器版本:Chrome 73.0.3683.103（正式版本） （64 位）
扩展版本:1.2.1（正式版）

**Comment by jjj201200** [comment]
@xxxxuanran 可以，下个版本中会改进，但是仍旧不能根本上解决问题

**Comment by jjj201200** [comment]
该问题可能已经在1.2.2.7版本中得到解决，请更新以验证此问题

**Comment by longwusha** [comment]
> 从官网下载的beta版，拖进扩展中显示**此扩展程序可能已损坏**。如何处理？

讲.crx文件重命名为.zip或.rar文件，解压后，扩展页面打开开发者模式，加载已解压的扩展
