### ISSUE TITLE
开启跨区域解锁影响直播区问题

### ISSUE THREAD

**Issue by yo846tt** [bilibili-helper/bilibili-helper#568]
## 问题反馈
只要开启主站跨区域解锁功能，直播区（为游客状态）无法正常发送弹幕等需要登录的功能，如果点击登录或直播个人中心也会出现登录界面与正常界面来回切换的情况！

### 环境信息
请填写以下信息:
1. 操作系统： Windows
2. 浏览器版本：360极速浏览器11.0（内核是Chrome69）
3. 扩展版本:version 1.2.1.4（正式版）

### 重现步骤/尝试的解决方案

关闭跨区域解锁就可以正常使用。

**Comment by yo846tt** [comment]
![image](https://user-images.githubusercontent.com/12368775/54286235-64efbc80-45de-11e9-95a0-4e8ac27e4e6d.png)
![image](https://user-images.githubusercontent.com/12368775/54286260-6faa5180-45de-11e9-915b-a9dd3ccbd251.png)

**Comment by yo846tt** [comment]
抱歉，无法截取GIF图，只要开启跨区域功能，点击到直播区需要登录的地方就会一直重复的出现如上面两张图片显示的页面！

**Comment by jjj201200** [comment]
请更换您使用浏览器，目前木法就win版本极速浏览器解决该问题

**Comment by wanguaf2016** [comment]
> 请更换您使用浏览器，目前木法就win版本极速浏览器解决该问题

您好，今天晚上突然在我的 Cent Browser 上也出现了这种情况。

**Comment by rosekc** [comment]
同遇到相同问题 拓展版本 1.2.1.8，chrome版本72.0.3626.12

**Comment by jjj201200** [comment]
与 #567 重复，故关闭，请勿重复提交相同问题的issue。
