### ISSUE TITLE
1.2.1.4版本每次检测都说有更新，但目前网页看应该是最新版本

### ISSUE THREAD

**Issue by Eviill** [bilibili-helper/bilibili-helper#569]
2019年3月14日00:11:04
https://bilibili-helper.github.io/
这个网页显示的是最新就是我安装的版本，每次打开网页都会提示有更新的版本，不知道为啥

网页登陆了B站账号 但是在上面的网页还是显示我没登陆 不知道为什么

**Comment by jjj201200** [comment]
请按照模板填写您目前使用的浏览器和助手使用情况，谢谢

**Comment by Eviill** [comment]
> 请按照模板填写您目前使用的浏览器和助手使用情况，谢谢

我又写了一份，抱歉我不知道怎样删除这一贴
