### ISSUE TITLE
1.2.1.4版本每次检测都说有更新，但目前网页看应该是最新版本

### ISSUE THREAD

**Issue by Eviill** [bilibili-helper/bilibili-helper#572]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [ ] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [ ] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [ ] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [ ] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):win10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):chrome版本 67.0.3396.87
3. 扩展版本:BILIBILI HELPER version 1.2.1.4（正式版）

https://bilibili-helper.github.io/
这个网页显示的是最新就是我安装的版本，每次打开网页都会提示有更新的版本，不知道为啥

网页登陆了B站账号但是在上面的网页还是显示我没登陆不知道为什么

![Uploading TIM截图20190314124450.png…]()
![TIM截图20190314124429](https://user-images.githubusercontent.com/38378557/54331954-17fbfc80-4657-11e9-9709-ada4abe1dd5a.png)
![TIM截图20190314124413](https://user-images.githubusercontent.com/38378557/54331955-18949300-4657-11e9-92d3-4def702a55d8.png)

**Comment by jjj201200** [comment]
弹出undefined这个bug会在测试版中修复

**Comment by jjj201200** [comment]
关于登录不上的问题，请更新浏览器到最新版本

**Comment by jjj201200** [comment]
1.2.1.7版本已经发布，请前往更新，如果还有问题，感谢您的再次反馈
