### ISSUE TITLE
[bug反馈]插件视频推送显示不完整

### ISSUE THREAD

**Issue by AiryC7** [bilibili-helper/bilibili-helper#573]
## 问题反馈
- 插件视频推送显示不完整

### 环境信息
1. 操作系统 : win10
2. 浏览器版本 : cent browser 3.8.5.69（正式版本） （64 位） (Chromium 71.0.3578.98)
3. 扩展版本:BILIBILI HELPER version 1.2.1.4（正式版）

### 重现步骤/尝试的解决方案
- 重装浏览器
- 重装浏览器插件
- 只启用bilibili助手插件
- 在无痕模式下启用bilibili助手插件
![QQ图片20190317091307](https://user-images.githubusercontent.com/40071520/54483806-ff792580-4894-11e9-9821-d49b346dbd39.png)

**Comment by AiryC7** [comment]
![QQ图片20190317091307](https://user-images.githubusercontent.com/40071520/54483816-38b19580-4895-11e9-84a7-ec6e250bbd78.png)

**Comment by jjj201200** [comment]
感谢反馈，之后会把滚动条隐藏掉，以显示完整的内容。

**Comment by jjj201200** [comment]
1.2.1.7测试版中已经修复此问题，请以测试版本安装方法进行安装。
