### ISSUE TITLE
直播间开启版聊模式后全屏出现问题

### ISSUE THREAD

**Issue by wanguaf2016** [bilibili-helper/bilibili-helper#574]
## 问题反馈
直播间开启版聊模式后，网页全屏使用时没问题，但全屏模式下无法显示版聊效果、无法显示弹幕、无法输入弹幕且有黑边。
![TIM截图20190318093617](https://user-images.githubusercontent.com/24241314/54501868-b55e7580-4962-11e9-985f-d57739d41283.png)
网页全屏模式下一切正常
![TIM截图20190318093628](https://user-images.githubusercontent.com/24241314/54501869-b8596600-4962-11e9-8436-160f363ea182.png)
全屏模式下异常

### 环境信息
1. 操作系统: Windows 10 Enterprise 17763.379
2. 浏览器版本: Cent Browser 3.9.2.33（正式版本） （64 位） (Chromium 72.0.3626.121)
3. 扩展版本: 1.2.1.4

### 重现步骤/尝试的解决方案
已尝试关闭广告拦截插件、关闭直播间相关脚本、清除浏览器缓存并重新加载页面、重新安装拓展等，皆未解决问题。

**Comment by jjj201200** [comment]
该功能暂时只设计为支持网页全屏，浏览器全屏兼容之后再考虑哈，关于没有弹幕的问题，其实是因为助手在进入网页全屏时关闭了自动点击的“隐藏弹幕”按钮。我会调整这个自动隐藏弹幕的逻辑

**Comment by wanguaf2016** [comment]
> 该功能暂时只设计为支持网页全屏，浏览器全屏兼容之后再考虑哈，关于没有弹幕的问题，其实是因为助手在进入网页全屏时关闭了自动点击的“隐藏弹幕”按钮。我会调整这个自动隐藏弹幕的逻辑

好的，那黑边的问题怎么办啊，暂时只能全屏前把版聊关掉吗？

**Comment by jjj201200** [comment]
@wanguaf2016 调整后浏览器全屏下黑边会消失

**Comment by jjj201200** [comment]
已经在1.2.1中修复
