### ISSUE TITLE
使用助手时主站消息中心及直播区出现网络错误

### ISSUE THREAD

**Issue by MengLuoRJ** [bilibili-helper/bilibili-helper#575]
## 问题反馈

RT，该问题发生于主站消息中心和直播区。
从 2019/03/20 00:05:00 左右后开始发生，此前（2019/03/19）并未发生该问题。
问题发生时，助手版本为 1.2.1.4，尚不知此前助手版本为多少。

**主站消息中心：**
进入我的消息页面后，消息发布者缺少头像，并且右下方提示网络错误。
`网络错误：api.live.bilibili.com/user/v2/User/getMultiple Error: Network Error`

[![AuffUS.th.png](https://s2.ax1x.com/2019/03/20/AuffUS.th.png)](https://imgchr.com/i/AuffUS) 

**直播区：**
无法正常显示个人信息，包括但不限于头像、经验等。

[![AufWE8.th.png](https://s2.ax1x.com/2019/03/20/AufWE8.th.png)](https://imgchr.com/i/AufWE8) 
[![Aufh4g.th.png](https://s2.ax1x.com/2019/03/20/Aufh4g.th.png)](https://imgchr.com/i/Aufh4g)

### 环境信息
1. 操作系统：Windows 10
2. 浏览器版本：Google Chrome 73.0.3683.75 x64
3. 扩展程序版本：BILIBILI HELPER version 1.2.1.4（正式版）

### 重现步骤/尝试的解决方案

**重现步骤：**
主站消息中心：在主站消息中心进入"我的消息页面"，即可看到右下脚报错提示，并且消息发布者缺少头像。
直播区：直接进入直播区首页，即可发现无法正常显示个人信息，包括但不限于头像、经验等。

**尝试的解决方案：**
将助手关闭后，以上问题均立即得到了解决。

### 补充内容
部分报错截图：
[![AuhS29.th.png](https://s2.ax1x.com/2019/03/20/AuhS29.th.png)](https://imgchr.com/i/AuhS29)

**Comment by MengLuoRJ** [comment]
这是一个错误的 Issue 报告。已经关闭。
测试时，出现报告中所提到的问题，关闭助手后，问题解决，且再次开启助手后，错误再次发生。
因此，发出以上 Issue 报告。尚未检查开发者工具下所获得的报错。
但在，之后的测试中发现，在助手持续开启的过程中（无论开/关任何一项设置）均未再次发生以上问题。进而认定以上 Issue 报告中问题是由B站服务器所导致的。
因此，已关闭该错误的 Issue 报告

**Comment by jjj201200** [comment]
你好，如果你开启了“跨区域解锁”功能，可能会发生这个情况？我认为有必要进一步确认，因为这个功能会重定向api接口的ip地址导致一些意料之外的问题。问题发生的可能性取决于使用的ip是否合适

**Comment by MengLuoRJ** [comment]
事件二次发生。时间 2019年3月24日 10:28 UTC

**环境信息**
操作系统：Windows 10
浏览器版本：Google Chrome 73.0.3683.86 x64
扩展程序版本：BILIBILI HELPER version 1.2.1.8（正式版）

**网络信息**
四川成都 电信 100Mbps

**Comment by MengLuoRJ** [comment]
已定位该问题。经过该次问题发生，已经定位该问题由功能“跨区域解锁”所导致。
经过在开发者临时提供的测试版本中，该问题得到了有效的解决。

但，目前仍存在因“跨区域解锁”功能所导致的B站全局加载减慢（加载初期，受重定向影响）的问题。

**具体问题：**
“跨区域解锁”功能使用助手时主站消息中心及直播区出现网络错误

**解决方案：**
更新至**最新版本的助手**，如使用的版本已经最新、无法得到更新，请**关闭“跨区域解锁”功能**以正常使用。
如果确实需要使用，请尝试**多次重启“跨区域解锁”功能、多次重启助手扩展程序并且重启游览器**

**Comment by jjj201200** [comment]
duplicate #567
