### ISSUE TITLE
【bug】直播领瓜子通知关闭后重启chrome会自动打开

### ISSUE THREAD

**Issue by luochengzhi089757** [bilibili-helper/bilibili-helper#576]
直播-自动领瓜子-推送通知
这个按钮点关闭以后可以生效，但是chrome重启以后会自动打开
关闭自动领瓜子后，重启chrome不会自动打开

助手版本：1.2.1.8
chrome版本：73.0.3683.86(X64)

**Comment by jjj201200** [comment]
请尝试卸载所有版本后重新安装

**Comment by jjj201200** [comment]
duplicate #579
