### ISSUE TITLE
测试版下载安装后提示损坏

### ISSUE THREAD

**Issue by VenomBat** [bilibili-helper/bilibili-helper#577]
![image](https://user-images.githubusercontent.com/48112300/54862951-2cd63f80-4d7d-11e9-95ed-47dc2f8e9fb2.png)

**Comment by VenomBat** [comment]
无法修复

**Comment by jjj201200** [comment]
请按照测试版本的安装方法进行安装，具体步骤查看官网下载区的【安装方法】
