### ISSUE TITLE
反映一个从1.2.0以来一直存在未修复的BUG

### ISSUE THREAD

**Issue by sll523911** [bilibili-helper/bilibili-helper#579]
### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):Windows10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):QQ浏览器最新版、360极速浏览器最新版
3. 扩展版本:1.2.1.10

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
![image](https://user-images.githubusercontent.com/45690827/54896754-992d7c00-4f00-11e9-9d54-c8a04289a124.png)
很简单的一个100%复现BUG，自动领瓜子的推送通知无法保存关闭，即“推送通知”关闭后，重启浏览器会再次自动打开。不管是全新安装还是各类浏览器版本都存在问题，本人4台电脑都出现这问题。

**Comment by jjj201200** [comment]
emmmm，确实存在一个重大bug，我正在推第11个测试版，请稍等

**Comment by jjj201200** [comment]
请更新至1.2.1-beta.11

**Comment by sll523911** [comment]
> 请更新至1.2.1-beta.11

问题依旧，重启浏览器后仍然会自动打开，四台电脑都是如此。

**Comment by jjj201200** [comment]
已经在1.2.1中修复
