### ISSUE TITLE
1.2.1.11_弹幕功能异常

### ISSUE THREAD

**Issue by xiaotongyyy** [bilibili-helper/bilibili-helper#580]
## 问题反馈
1.弹幕功能问题（1.2.0版本预告中的问题未解决）
  (a) 弹幕功能不能正常工作，显示“无数据”；
  (b) 查询弹幕内容处删除输入的最后一个字符后整个弹幕功能区域会消失。测试过中文、英文、数字、符号均会触发这个问题。

2.非BUG问题
  (a) （issue#553）2018年下半年某个时间点之后的视频无法获取下载选项，请问这个问题下一个版本会修复么？
  (b) （issue#552）旧版播放页面无法正确加载助手菜单，请问旧版本播放器这个问题还会有修复么？新版播放器可以正确加载图标，只是个人还是喜欢旧版播放器多一些。

### 环境信息
操作系统：Windows 10 Pro (1803)
浏览器：Chrome Version 73.0.3683.86 (Official Build) (64-bit)
插件版本：1.2.1.11（正式版）
*浏览器中已关闭Bilibili助手以外其他extension及app。

### 重现步骤/尝试的解决方案
Bilibili新版播放器右侧打开助手菜单后弹幕功能无法工作：
![1](https://user-images.githubusercontent.com/31784425/54974671-d591c400-4f62-11e9-9815-99c54c4a8c25.PNG)
![2](https://user-images.githubusercontent.com/31784425/54974675-d9254b00-4f62-11e9-9786-842dacf1cc16.PNG)
删除最后一位字符后弹幕相关区域消失：
![3](https://user-images.githubusercontent.com/31784425/54974677-daef0e80-4f62-11e9-8e72-091c91a98b74.PNG)

**Comment by jjj201200** [comment]
请问这个问题是出现在所有视频播放页面中吗

**Comment by xiaotongyyy** [comment]
> 请问这个问题是出现在所有视频播放页面中吗

目前打开过的大概10个视频页面都遇到上述两个弹幕功能的问题。

**Comment by jjj201200** [comment]
可以发一个遇到问题的链接吗

**Comment by xiaotongyyy** [comment]
> 可以发一个遇到问题的链接吗

https://www.bilibili.com/video/av47368220

**Comment by jjj201200** [comment]
请发一下这个开发者界面的截图
![image](https://user-images.githubusercontent.com/3397549/54976659-00693000-4fd6-11e9-8945-8c16424eae64.png)

**Comment by xiaotongyyy** [comment]
> 请发一下这个开发者界面的截图
![Capture](https://user-images.githubusercontent.com/31784425/54976968-ebef4e00-4f69-11e9-9d2a-36aece70cfc5.PNG)

**Comment by jjj201200** [comment]
截图显示你目前安装的版本仍旧为1.2.0，请更新到最新测试版本，建议删除正式版本后重新安装测试版

**Comment by xiaotongyyy** [comment]
> 请发一下这个开发者界面的截图


我当前的site permission如下：
![Capture3](https://user-images.githubusercontent.com/31784425/54977176-83ed3780-4f6a-11e9-94d2-605903d9c7ba.PNG)
是否需要我尝试reset permissions？

**Comment by xiaotongyyy** [comment]
> 截图显示你目前安装的版本仍旧为1.2.0，请更新到最新测试版本，建议删除正式版本后重新安装测试版

我是今天刚在Chrome商店中下载安装的，extension options中显示的版本是版本 1.2.1.11（正式版），可能是一个BUG。
正在尝试重新安装测试版。

**Comment by jjj201200** [comment]
这个问题应该是出现在同时保留多个版本的时候，不同版本之间的配置会有却别，所以会有这个问题

**Comment by xiaotongyyy** [comment]
> 截图显示你目前安装的版本仍旧为1.2.0，请更新到最新测试版本，建议删除正式版本后重新安装测试版

感谢指导！
安装1.2.1.11测试版之后问题解决，视频与字幕可以正常下载/搜索。
期待1.2.1正式版的发布，麻烦你改个label。

**Comment by jjj201200** [comment]
没事没事，这个issue我就关了哈
