### ISSUE TITLE
夜间模式下个别文字颜色有误

### ISSUE THREAD

**Issue by WANGJIEKE** [bilibili-helper/bilibili-helper#581]
### 环境信息
1. 操作系统 (Windows/macOS/Linux): macOS Mojave 10.14.4
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Chrome 73.0.3683.86 (Official Build) (64-bit)
3. 扩展版本: version 1.2.1.11（正式版）

### 重现步骤
1. 启用夜间模式
2. 点击某条评论下方的“共xxx条回复，点击查看”
3. 拉到当前评论回复页面的底端，发现回复分页的按钮颜色没有被调整为浅色

![issue](https://user-images.githubusercontent.com/21030118/55040056-14b42980-4fe4-11e9-89bd-83e81828f5bc.png)

**Comment by jjj201200** [comment]
感谢反馈~~

**Comment by jjj201200** [comment]
以在1.2.1中修复
