### ISSUE TITLE
开启跨区域解锁时主站播放出现问题（播放器网络错误403）

### ISSUE THREAD

**Issue by lookas2001** [bilibili-helper/bilibili-helper#582]
Edited (zacyu): Removed technical details not really for public disclosure.

开启跨区域解锁时，主站播放一定时间后播放器提示403错误。

开启跨区域解锁会导致 bilibili 将视频播放的 cdn 调度到 upos-hz-mirrorwcsu.acgvideo.com 这台服务器，经过简单测试发现这台服务器对访问频率限制的比较厉害，在一定量的请求后会返回 403 。

重现

打开跨区域解锁选项。
打开任意一个视频，播放，多拉动几下进度条。
403。

一些可能有用的信息

我这里解析的结果：

www.bilibili.com 119.3.227.169
upos-hz-mirrorwcsu.acgvideo.com 117.131.205.5

插件、浏览器、系统版本信息：

bilibili helper 1.2.1.13
Chrome 73.0.3683.86
macOS Mojave 10.14.3

另外，这段时间看直播间礼物那里好像也挂了，不过看好像有 issue 提了。qwq

**Comment by jjj201200** [comment]
你好请问您的坐标位于哪里，我在上海一直没有这个问题。我觉得应该是你说的原因，但是目前无法复现。也没有想到有效的解决办法。测试版本中已经更换了3个ip，而最新的一个就是你正在使用的beta13版。该功能需要我们通过一个足够稳定可靠的ip，从而不会导致一些功能失效。目前，如果您不是经常需要使用该功能的话，只能麻烦你先关闭该功能了，我们会继续调查原因，搜集更多反馈来解决这个潜在的问题。

**Comment by lookas2001** [comment]
天津移动。刚刚试了一下，确实没法重现了。
前一段时间在刚出现问题定位不到问题原因的时候有根b站客服反馈过，不大清楚是否后来有人修复了这个问题。
另外，能否在功能开关下面的描述内加入一行说明，因为这个功能好像会影响到 b 站的 cdn 调度，在网络条件比较复杂的情况下，可能会导致一些不容易发现的问题。

**Comment by jjj201200** [comment]
我已经在官网更新内容中添加说明，暂时就不再发版在助手中更新这个说明了

**Comment by jjj201200** [comment]
该issue我关了哈，和#567 重复了
