### ISSUE TITLE
偶发性导致直播页面异常

### ISSUE THREAD

**Issue by zzy5156** [bilibili-helper/bilibili-helper#583]
### 环境信息
1. 操作系统:Windows 10 1803
2. 浏览器版本:Cent Broswer 版本 3.9.2.45（正式版本） （32 位） (Chromium 72.0.3626.121)
3. 扩展版本:version 1.2.1（正式版）

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
暂时没有发现100%复现的方法，貌似是更新1.2.0之后就开始偶然出现了
![屏幕截图(232)](https://user-images.githubusercontent.com/49281709/55565513-8864dd80-572c-11e9-88e5-5711e524cadf.png)
如图，动态页面的“正在直播”没了
![屏幕截图(233)](https://user-images.githubusercontent.com/49281709/55565589-ac282380-572c-11e9-8d6d-ca508f1d5f55.png)
“动态”里的“直播”也一直是Loading
![屏幕截图(234)](https://user-images.githubusercontent.com/49281709/55565637-c6fa9800-572c-11e9-80fb-ee2a8a0993b2.png)
手动输入地址可以看直播，但也仅仅只能看直播，送礼物，发弹幕等功能全部不能用。
附上直播相关的设置
![屏幕截图(236)](https://user-images.githubusercontent.com/49281709/55565983-6d469d80-572d-11e9-9af1-fb1c4b8a8617.png)
![屏幕截图(237)](https://user-images.githubusercontent.com/49281709/55566006-72a3e800-572d-11e9-8a9a-84a64906004d.png)
禁用助手后刷新页面立刻恢复正常。目前唯一找到的解决方法就是重启电脑。不重启的话只要一启用助手就出现上述问题。因为我只有一台电脑所以不确定是否为个例

**Comment by jjj201200** [comment]
你好，该问题与#567 重复。
在此，简要回答您的反馈：由于暂时无法确定的原因，如果在使用过程中碰到了一些问题，请尝试关闭跨区域限制解锁功能，我们会持续关注该功能导致的一系列问题和其解决方案，如果您有什么主意或者可以提供有用的信息。
