### ISSUE TITLE
IDM插件功能问题，能否修复一下

### ISSUE THREAD

**Issue by 954455850** [bilibili-helper/bilibili-helper#585]
IDM的下载悬浮条在启用插件后无法抓捕B站视频，把助手禁用后IDM的悬浮条可以正常工作来抓捕B站视频

1. 操作系统 Windows10
2. 浏览器chrome
3. 扩展版本:1.2.1

**Comment by 954455850** [comment]
启用插件前
![image](https://user-images.githubusercontent.com/31529293/56092345-b3e68580-5eed-11e9-833a-ce2cdd7e8050.png)

**Comment by 954455850** [comment]
启用插件后IDM无法正常工作
![image](https://user-images.githubusercontent.com/31529293/56092362-d7a9cb80-5eed-11e9-93b5-1f54f2294e18.png)

**Comment by 954455850** [comment]
设置
![image](https://user-images.githubusercontent.com/31529293/56092377-0f187800-5eee-11e9-9570-dbfbea986bd5.png)
![image](https://user-images.githubusercontent.com/31529293/56092380-13dd2c00-5eee-11e9-98b1-38dffd2d227d.png)
![image](https://user-images.githubusercontent.com/31529293/56092382-18094980-5eee-11e9-8e02-b1d922911281.png)
![image](https://user-images.githubusercontent.com/31529293/56092386-1fc8ee00-5eee-11e9-82c4-a1ee5bfa723e.png)

**Comment by jjj201200** [comment]
请尝试关闭“跨区域解锁”功能

**Comment by jjj201200** [comment]
1.2.2.7版本那种修复了该问题，请更新以解决此问题

**Comment by jjj201200** [comment]
fixed in  v1.2.3
