### ISSUE TITLE
扩展影响B站网页加载

### ISSUE THREAD

**Issue by sickneet** [bilibili-helper/bilibili-helper#586]
动态里的直播一栏无法加载
![image](https://user-images.githubusercontent.com/30150112/56094419-ccaf6500-5f06-11e9-92e0-f02fcc0940ae.png)
消息中心里左侧一栏里所有项目均有同一个网络错误
![image](https://user-images.githubusercontent.com/30150112/56094447-10a26a00-5f07-11e9-8fae-bd516eee89fc.png)
扩展还影响B站直播，导致直播无法观看，或部分直播无法加载视频或网页
![image](https://user-images.githubusercontent.com/30150112/56094513-c79ee580-5f07-11e9-98c2-6aae7c73dba2.png)
所有问题在chrome隐身模式下都正常，经排查所有浏览器扩展，关掉助手之后就好了

**Comment by jjj201200** [comment]
请关闭“区域限制解锁功能”，该问题与 #567 重复。
