### ISSUE TITLE
只要启用本扩展就会出现视频小窗被右侧栏覆盖

### ISSUE THREAD

**Issue by FoobarRogers** [bilibili-helper/bilibili-helper#587]
请保留一种您需要的语言版本的报告模板
please leave only one kind of these template

## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:

1. 操作系统 (Windows/macOS/Linux): win10 1809 17763.437
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):chrome 73.0.3683.103 x64版
3. 扩展版本:1.2.1

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
只要启用本扩展就会出现小窗被右侧栏覆盖的bug，已在无痕模式下测试，已尝试关闭所以可关闭选项。禁用扩展即恢复正常

启用扩展
![屏幕截图(3)](https://user-images.githubusercontent.com/25246983/56328725-dceb6c80-61b2-11e9-8c5f-a9c5a0413bd1.png)
禁用扩展
![image](https://user-images.githubusercontent.com/25246983/56328790-2471f880-61b3-11e9-8f6c-ec33bda80487.png)

请具体描述, 谢谢 :)

**Comment by jjj201200** [comment]
fixed in  v1.2.3
