### ISSUE TITLE
“关闭动态页面小视频自动播放”功能无效

### ISSUE THREAD

**Issue by galaxy9064** [bilibili-helper/bilibili-helper#589]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [ ] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [ ] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [ ] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [ ] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统版本 Windows 7 SP1
2. 浏览器版本 69.0.3497.100（正式版本） （64 位）
3. 扩展版本 version 1.2.1（正式版）

### 重现步骤/尝试的解决方案
在助手选项页-其它-勾选“关闭动态页面小视频自动播放”功能后，刷新动态页面，小视频依然会自动播放。
反复关闭开启此功能后依然无效，请开发者予以帮助，谢谢！

**Comment by jjj201200** [comment]
感谢反馈，b站定是又双叒改了什么

**Comment by jjj201200** [comment]
fixed in  v1.2.3

**Comment by galaxy9064** [comment]
> fixed in v1.2.3

谢谢开发者的努力！注意到扩展程序图标已经更新了
