### ISSUE TITLE
右键哔哩哔哩搜索无法关闭

### ISSUE THREAD

**Issue by LuckyRabbitFeet** [bilibili-helper/bilibili-helper#590]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
Browser: Google Chrome
version: 73.0.3683.103
bilibili-helper version: 1.2.1

在设置中选择关闭右键哔哩哔哩搜索后，右键菜单还是会有此功能项。

**Comment by jjj201200** [comment]
fixed in  v1.2.3
