### ISSUE TITLE
Feature request: 允许专栏文字选中

### ISSUE THREAD

**Issue by reorx** [bilibili-helper/bilibili-helper#593]
目前专栏文字是不能被鼠标直接选中的，只能通过 Inspect Element 来获取，查明是由以下代码导致:

```
// css
.article-holder.unable-reprint {
    user-select: none;
    -webkit-user-select: none;
}

// html
<div class="article-holder unable-reprint">
```

将 `unable-reprint` class 去掉，或者 `!important` overwrite 其 css 即可解决。

**Comment by jjj201200** [comment]
您可以提交该module的pull，我将会合并此功能。
在此建议增加专栏相关的综合栏目，并将此功能与图片下载作为子功能，以便后续添加更多专栏相关的功能。

**Comment by reorx** [comment]
如果能够的话我很乐意直接提 PR 而不是 issue，但由于我对前端的了解仅限基本的 JavaScript，对 React 更是一窍不通，因此开发起来会非常有难度。还请作者有空时支持一下啦🙏。

**Comment by Preliterate** [comment]
我还是觉得设置个开关，然后
`document.getElementsByClassName('article-holder')[0].classList.remove('unable-reprint')`

**Comment by jjj201200** [comment]
这个我已经在测试版中加上去了，和专栏图片下载合并在一个开关里，我觉得没什么问题，如果专栏以后有更多功能点再分开也不迟。
