### ISSUE TITLE
追番推送提醒影响体验

### ISSUE THREAD

**Issue by RANSUROTTO** [bilibili-helper/bilibili-helper#596]
如题，选项并没有该设置。平常开着浏览器打LOL。chrome推送会成win10弹框，对游戏玩家不友好。

**Comment by longwusha** [comment]
这个是bilibili自己的推送消息，你可以在chrome里面禁止bilibili推送通知。我也碰到过，通知一出，你不切出去关掉，小地图就看不到了，一切出去，来回就要卡几秒。。。

**Comment by jjj201200** [comment]
chrome从60+的某个版本开始推送改用系统原生的推送窗口，这个改不了了。如@longwusha 所说你可以在浏览器里关闭推送。没有其它问题的话，请关闭该issue哦~

**Comment by xmcp** [comment]
@jjj201200 到现在的Chrome74为止还可以禁用掉 `chrome://flags/#enable-native-notifications` 来改回原来的通知

**Comment by jjj201200** [comment]
@xmcp 感谢告知~
