### ISSUE TITLE
夜间模式下部分弹幕相关按钮有误。

### ISSUE THREAD

**Issue by Wcraft233** [bilibili-helper/bilibili-helper#599]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):Windows 10 1809 17763.292
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):74.0.3729.157（正式版本） （64 位）
3. 扩展版本:1.2.1

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
在一个属于你的视频下展开弹幕窗口，部分up操作用的按钮仍是白底，且弹幕文字仍为黑色难以看见。
![图片](https://i.loli.net/2019/05/24/5ce7eade2f98061080.jpg)

**Comment by jjj201200** [comment]
fixed in  v1.2.3
