### ISSUE TITLE
 自动领瓜子会卡在'载入中'的状态

### ISSUE THREAD

**Issue by qsdaqsdafqr** [bilibili-helper/bilibili-helper#604]
1.2.1正式版
win10.1803 64位
Chrome版本为75.0.3770.100
![image](https://user-images.githubusercontent.com/40647452/60042175-ab7da880-96ef-11e9-8bf0-b010da78636c.png)

**Comment by jjj201200** [comment]
请尝试1.2.1.7测试版本

**Comment by moqiaoduo** [comment]
该问题可能是资源加载的问题，可以尝试在开发者工具（F12）中选择Network选项，勾选Disable cache，然后刷新至正常位置。同为1.2.1正式版。

**Comment by hoxxer** [comment]
可以将chrome升级到76

**Comment by aclihub** [comment]
有可能是你同时开了多个直播间

**Comment by jjj201200** [comment]
fixed in  v1.2.3
