### ISSUE TITLE
【功能请求】恢复b站评论楼层显示

### ISSUE THREAD

**Issue by redapple0204** [bilibili-helper/bilibili-helper#606]
没有楼层显示太蛋疼了= =

**Comment by jjj201200** [comment]
貌似已经获取不到这个字段的数据了

**Comment by jjj201200** [comment]
没有楼层显示具体会带来什么困扰，可否具体阐述一下

**Comment by redapple0204** [comment]
@jjj201200 举个例子，在许多地方（例如萌娘百科）对于某些事件的索引和出处都是按照b站某个视频楼层叙述的（比如在avxxx中#250出现了某某言论）如果没有楼层将会很不好找

**Comment by jjj201200** [comment]
@redapple0204 如果是指一种代号的话，其实是有评论id的，可以显示出来，有必要的话这个可以一试

**Comment by redapple0204** [comment]
不是代号，这里的#250指的是250楼

DrowsyFlesh <notifications@github.com> 于2019年7月5日周五 下午11:16写道：

**Comment by jjj201200** [comment]
@redapple0204 那没有办法咯，issue我关了哈

**Comment by starxjys** [comment]
这个好像还是可以的，win10商店里面有一个第三方的客户端，可以楼层显示，开源项目
