### ISSUE TITLE
关于新版番剧页面迷你播放器的bug

### ISSUE THREAD

**Issue by moqiaoduo** [bilibili-helper/bilibili-helper#607]
## 问题反馈
迷你播放器在新版番剧页面上工作不正常，且为插件开启时才发生。
具体为：在相关视频推荐列表与迷你播放器重合时，迷你播放器并不置顶，而是在推荐列表的下层；评论区也会挡住迷你播放器。（见附件图）

### 环境信息
请填写以下信息:
1. 操作系统:Windows
2. 浏览器版本:75.0.3770.100(64位)
3. 扩展版本:1.2.1

### 重现步骤/尝试的解决方案
不启用插件时，该问题不存在；启用插件时，该问题存在。

P.S. 关于这个bug，个人猜测是层叠样式表（CSS）出现了冲突，不过本人暂无精力去查看代码，所以无法定位问题所在，麻烦作者修复了。
![TIM截图20190706125532](https://user-images.githubusercontent.com/20296531/60751802-bb01c900-9fee-11e9-8710-87cae7e7ee54.png)
![TIM截图20190706125456](https://user-images.githubusercontent.com/20296531/60751806-bfc67d00-9fee-11e9-8885-a8c3d2810404.png)

**Comment by jjj201200** [comment]
duplicate #587
