### ISSUE TITLE
自动领瓜子 领取中 会使页面卡住

### ISSUE THREAD

**Issue by Teachoc** [bilibili-helper/bilibili-helper#620]
### 环境信息
1. 操作系统: Windows 10 1903
2. 浏览器版本: Microsoft Edge 版本 78.0.276.2 (官方内部版本) dev (64 位)
3. 扩展版本: 版本 1.2.1（正式版）

**Comment by jjj201200** [comment]
非稳定版本我们就暂时先放一下哈，抱歉。

**Comment by ChromeHu** [comment]
我也有这情况，然后领瓜子访问失败就一直重试，导致看直播一卡一卡的。


Microsoft Edge 78.0.276.11 (官方内部版本) beta (64 位)
1.2.1（正式版）

**Comment by popboyhsf** [comment]
我也有这情况，自动领瓜子阶段会卡分页进程导致整个分页无响应。Orz
77.0.3865.90 (正式版本) (64 位元)
version 1.2.1（正式版）

**Comment by geektheripper** [comment]
![image](https://user-images.githubusercontent.com/7630993/66715776-da806d00-edf9-11e9-806a-e1954f46a782.png)

**Comment by jjj201200** [comment]
@geektheripper 被你发现了，之前有用户反馈了这个问题，已经优化但没有发出来。
