### ISSUE TITLE
夜间模式下，侧边正常弹幕淡化，屏蔽弹幕显著

### ISSUE THREAD

**Issue by zhihuo0120** [bilibili-helper/bilibili-helper#622]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [ ] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 :windows
2. 浏览器版本 : Google Chrome77.0.3865.90

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
1.打开夜间模式
2.打开侧边栏的弹幕
3.显示如下（侧边正常弹幕淡化，屏蔽弹幕显著）
![image](https://user-images.githubusercontent.com/48322854/66265667-d201c280-e84c-11e9-8cae-eb5d47f2dbec.png)
4.正常情况下
![image](https://user-images.githubusercontent.com/48322854/66265675-fa89bc80-e84c-11e9-8514-9691622dc977.png)

**Comment by jjj201200** [comment]
emmmmm还真是，感谢反馈，请给一下你截图的这个视频aid可以吗

**Comment by zhihuo0120** [comment]
https://www.bilibili.com/video/av70252030

**Comment by jjj201200** [comment]
更新1.2.2.13看看吧~

**Comment by jjj201200** [comment]
fixed in  v1.2.3
