### ISSUE TITLE
当将可访问的网址的权限限制了之后，插件工作不正常了

### ISSUE THREAD

**Issue by PussAzuki** [bilibili-helper/bilibili-helper#629]
## 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):
Windows 10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):
78.0.3904.70
3. 扩展版本:
目前在用谷歌商店版的1.2.1(，但似乎能发生在任意版本？)

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
先按照哔哩哔哩助手官网的教程安装上哔哩哔哩助手，接着去B站将账号登录上，并查看插件及确定此时能使用哔哩哔哩助手设置页面的账号登陆相关的功能；接着从chromium系浏览器那边的extension界面进入插件管理界面，将哔哩哔哩助手的site access项目限制在 https://*.bilibili.com/* 和 https://bilibili-helper.github.io/* 两项，接着关闭浏览器，再打开，会发现插件这边会变成未登录状态。

理论上需要能读取网址数据的也就我提到的这两个才对，为什么会发生未登录的状态的这种情况呢？

**Comment by jjj201200** [comment]
理论上远远不止你提到的那两个~

**Comment by PussAzuki** [comment]
https://*.hdlsb.com/* 也加进去了...但是也没用...还是提示未登录
我还用了https everywhere的插件，理论上除了那个bbs应该都是https了...

**Comment by PussAzuki** [comment]
github这怎么把*这个符号当特殊用途了啊...|
[我的做法](https://i.loli.net/2019/10/30/VQYPMrl5Gohbkwa.png)

**Comment by jjj201200** [comment]
我试了一下，没问题啊，你关了其他的试试

**Comment by PussAzuki** [comment]
这就很奇怪了...换成你的通配符之后还是不行...我不觉得是油猴脚本的问题...毕竟之前全都允许的时候是可以共存的

**Comment by jjj201200** [comment]
@PussAzuki 是不是你排除法关掉一下就知道了

**Comment by PussAzuki** [comment]
我没关...然后现在正常了？我嗦不出话
