### ISSUE TITLE
建议添加一个跳过充电鸣谢的功能

### ISSUE THREAD

**Issue by happyTonakai** [bilibili-helper/bilibili-helper#631]
现在每个视频结束都会弹出一个5秒的充电鸣谢功能，跳过按钮是在屏幕的右上角，而取消全屏的按钮在屏幕的右下角，如果不想伸手按ESC的话每次都要纵跨屏幕点两下很麻烦…… 能否加入自动跳过充电鸣谢界面的功能呢

**Comment by jjj201200** [comment]
这个功能对充电者不友好，也就是对支持视频作者的人不友好，好像没有什么十分充足的理由直接跳过
我想，你或许可以考虑别的方向来解决你的问题
