### ISSUE TITLE
点击我的收藏菜单，会进入个人空间，并不会进入收藏界面

### ISSUE THREAD

**Issue by Yangself666** [bilibili-helper/bilibili-helper#632]
##点击我的收藏菜单，会进入个人空间，并不会进入收藏界面

## 问题反馈
点击我的收藏菜单，会进入个人空间，并不会进入收藏界面
### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):macOS
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Chrome 78.0.3904.108
3. 扩展版本:1.2.1

### 希望添加搜索框，av号不经常用，但是经常需要搜索

**Comment by jjj201200** [comment]
点击收藏打开的是
https://space.bilibili.com/{uid}/favlist
是个人空间的收藏页面，有哪里不对吗？你那边跳转到的是什么页面？

**Comment by Yangself666** [comment]
我这边进入的就是个人主页，https://space.bilibili.com/2838204，没有后面favlist

**Comment by Yangself666** [comment]
您看这个https://www.lanzous.com/i7iqb0h

**Comment by Yangself666** [comment]
更新了新版本，已经好了，麻烦您
