### ISSUE TITLE
安装此插件后使用浏览器进行文件或图片保存时存在严重延时

### ISSUE THREAD

**Issue by Squarelan** [bilibili-helper/bilibili-helper#633]
### 问题反馈
安装此插件后使用浏览器进行图片保存时存在严重延时，我把所有扩展全部关闭只开这一个扩展结果是一样的，开启插件和不开启插件是两种速度，最新发现文件保存也会存在延迟，只要是用浏览器自带的下载都会存在延迟

### 环境信息
1. 操作系统 (Windows/macOS/Linux): Windows 10 1909
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): 78.0.3904.108
3. 扩展版本:1.2.2

### 重现步骤/尝试的解决方案
随便找一个图片进行右键保存，在开启此插件的情况下保存窗口大概需要10秒钟才能出来。而在关闭此插件后，保存窗口大概只需要1~2秒就会出来

**Comment by imkyleshing** [comment]
是吧，我还以为是我的问题，清了一边浏览器

**Comment by davidan106** [comment]
同样的环境，浏览器版本也遇到了类似问题，在点击右键图片另存为时候 会延迟10秒左右下载

**Comment by levy258** [comment]
同上问题 已关闭插件等待修复 正在看这部剧时发现的http://live.bilibili.com/8735534

**Comment by gxytcgxytc** [comment]
同上 在尝试下载文件时，发出下载请求后，下载即刻开始，浏览器有绿色进度条在走，10秒左右弹出下载文件窗口（此时正在下载）

**Comment by jjj201200** [comment]
fixed in v1.2.3
