### ISSUE TITLE
Chrome 商店版1.2.3BUG会影响我所有别的下载插件

### ISSUE THREAD

**Issue by bob9692** [bilibili-helper/bilibili-helper#634]
只要开着哔哩哔哩助手，所有别的下载类插件（比如Pixiv Batch Downloader、Youtube Downloader、Twitter Media Downloader等等）调用chrome内建下载所下载的文件，文件名全部是乱七八糟的

**Comment by Squarelan** [comment]
这个确实是，用Pixiv Batch Downloader经测试文件名会乱的，下载延时倒是解决了

**Comment by jjj201200** [comment]
感谢反馈，目前已经知晓该问题是由于视屏下载功能中对视频文件名替换所致
我会尝试其他方案来实现这个需求，目前只能通过停用扩展来解决这个问题

**Comment by FaiChou** [comment]
![image](https://user-images.githubusercontent.com/18500846/69517518-eb430780-0f8f-11ea-8925-b70f9080e383.png)

**Comment by FaiChou** [comment]
修复后麻烦通知下 @jjj201200

**Comment by jjj201200** [comment]
[bilibilihelper_1.2.4-beta.1.crx.zip](https://github.com/bilibili-helper/bilibili-helper/files/3886885/bilibilihelper_1.2.4-beta.1.crx.zip)
试试这个 @bob9692 @Squarelan @FaiChou

**Comment by Squarelan** [comment]
@jjj201200 Pixiv Batch Downloader测试已修复，其他的不知道，应该是修复了

**Comment by jjj201200** [comment]
1.2.6版本已经发布，请及时更新~
