### ISSUE TITLE
直播版聊模式聊天菜单和视频控制菜单重叠

### ISSUE THREAD

**Issue by whynotjinx** [bilibili-helper/bilibili-helper#635]
大概情况如下图，几乎不能直接控制音量，虽然说可以切回普通模式进行调整，但是还是希望能稍微改进一下
![image](https://user-images.githubusercontent.com/33567283/69813203-d1cae580-1245-11ea-8c92-be09a00aa95a.png)

**Comment by jjj201200** [comment]
请检查一下您是否有其他样式修改扩展或者脚本正在运行

**Comment by whynotjinx** [comment]
试了一下，即使在无痕模式关闭所有除助手以外的插件下，还是这样
画面比例也调过了

**Comment by jjj201200** [comment]
好，能不能先根据issue模板填写一下相关信息，外加屏幕分辨率的信息

**Comment by whynotjinx** [comment]
### 环境信息
1. 操作系统: Windows 10 1909
2. 浏览器版本: chrome 78.0.3904.108
3. 扩展版本: 1.2.6 （正式版）
4. 屏幕分辨率：1080p

**Comment by jjj201200** [comment]
可否远程调试一下？我不确定是否是b站对直播区的灰测导致的样式差别，目前只能猜测几种样式导致的可能性，但由于无法复现并不能排除。或许我可能多相应的改动后发你测试包来排除一下（q群：548321019）
