### ISSUE TITLE
连续点击多次检查更新按钮会导致按钮变黑

### ISSUE THREAD

**Issue by HaoTian22** [bilibili-helper/bilibili-helper#640]
如题，按钮变黑后如图所示(此外貌似我点了检查更新没什么反应？)
![image](https://user-images.githubusercontent.com/48882584/70331361-43c0b180-187a-11ea-9137-f10a7cc8f5d9.png)

**Comment by jjj201200** [comment]
是火狐吗？火狐目前的版本由于接口问题会弹不出弹窗。我已经推了代码，但是还没在火狐发新包。

**Comment by HaoTian22** [comment]
Microsoft Edge
