### ISSUE TITLE
CC字幕不能下载

### ISSUE THREAD

**Issue by CloudyEagle** [bilibili-helper/bilibili-helper#643]
我在有CC字幕的视频想下载字幕，之前有一次下载成功过，不知道什么原因近期不能下载。
我可以保证这项设置了肯定是开着的。
![TIM截图20191211210814](https://user-images.githubusercontent.com/58777085/70625123-b9eb5c80-1c5c-11ea-8033-cf631ff3d1b5.png)

进入有CC的视频点击助手，在我的Edge Canary可以有弹幕和下载。在360极速浏览器中只有下载（弹幕功能开着的），而Google Chrome说是什么内核升级问题不能用，所以这个CC字幕下载到底是哪里问题？
![TIM截图20191211210611](https://user-images.githubusercontent.com/58777085/70625130-be177a00-1c5c-11ea-9357-885e9453e47d.png)
![TIM截图20191211210232](https://user-images.githubusercontent.com/58777085/70625136-c2439780-1c5c-11ea-8562-e2764e146ad4.png)

**Comment by jjj201200** [comment]
请你先按照问题提交模板填写一下基本信息，不要忽略模板~

**Comment by CloudyEagle** [comment]
环境信息：
操作系统 (Windows/macOS/Linux):WIN10
浏览器版本(您可以在 [菜单/帮助/关于] 下查看):360极速浏览器，Microsoft Edge Canary
扩展版本:1.2.9
重现步骤/尝试的解决方案
我在有CC字幕的视频想下载字幕，之前有一次下载成功过，不知道什么原因近期不能下载。
我可以保证这项设置了肯定是开着的。
![70625123-b9eb5c80-1c5c-11ea-8033-cf631ff3d1b5](https://user-images.githubusercontent.com/58777085/70789970-05be1300-1dcf-11ea-922d-fd2dbc05b329.png)
进入有CC的视频点击助手，在我的Edge Canary可以有弹幕和下载。在360极速浏览器中只有下载（弹幕功能开着的），而Google Chrome说是什么内核升级问题不能用，所以这个CC字幕下载到底是哪里问题？
360：
![70625136-c2439780-1c5c-11ea-8562-e2764e146ad4](https://user-images.githubusercontent.com/58777085/70790021-25edd200-1dcf-11ea-841e-2c64a2e05ff4.png)
Edge Canary：
![70625130-be177a00-1c5c-11ea-9357-885e9453e47d](https://user-images.githubusercontent.com/58777085/70790108-50d82600-1dcf-11ea-8392-b245f5aeefc3.png)
Goolge：
![TIM截图20191213173907](https://user-images.githubusercontent.com/58777085/70790198-8d0b8680-1dcf-11ea-946b-4c40f196c3ef.png)

**Comment by jjj201200** [comment]
请发一下相关的视频链接

**Comment by jjj201200** [comment]
请稍等，我发现这个功能确实出问题了。我将使用你提供的视频进行调试

**Comment by jjj201200** [comment]
下个版本将修复这个问题，已经确定到时由于b站改了获取字幕相关数据的接口导致数据没有获取到
感谢你的反馈~
