### ISSUE TITLE
建议上架新版Edge商店

### ISSUE THREAD

**Issue by JedSunCN** [bilibili-helper/bilibili-helper#657]
新版Edge已发布正式版，还请开发者大大跟进，谢谢。

**Comment by jjj201200** [comment]
在上了在上了😿

**Comment by ljcbaby** [comment]
同求（尽管Edge也可以装谷歌商店版

**Comment by jjj201200** [comment]
在审核嘛，人家很慢的啦Orz

**Comment by jjj201200** [comment]
<img width="1678" alt="WX20200201-001909@2x" src="https://user-images.githubusercontent.com/3397549/73572242-48d16400-44ab-11ea-9218-c6f24a21f86c.png">

**Comment by JedSunCN** [comment]
请问怎么还没有啊😂，人家隔壁的pakku都有了。(￣▽￣)"

**Comment by jjj201200** [comment]
@JedSunCN 应该是助手比较复杂的关系吧

**Comment by JedSunCN** [comment]
上架是不是凉了😂，到现在EDGE ADDONS里面还没有。。。

**Comment by ChinaVRally** [comment]
很期待啥时候有

**Comment by jjj201200** [comment]
https://microsoftedge.microsoft.com/addons/detail/fcfebhekhbkhjjimonjmbgmkbclheaoh?hl=zh-CN
Edge已经上架，同时请各位留意不要下错，还有一款盗版的被恶意修改的，请举报他
