### ISSUE TITLE
#在某些情况下直播间银瓜子自动领取失效（验证码无法自动填写）（之后暂未再次出现）

### ISSUE THREAD

**Issue by FUSIZHE** [bilibili-helper/bilibili-helper#664]
请保留一种您需要的语言版本的报告模板
please leave only one kind of these template

## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [ ] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [ ] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [ ] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):
3. 扩展版本:

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)

## Feedback
Before submitting your issue, please check to make sure of the following:
- [ ] You are reporting a bug or making a feature request. If you are looking for general support, please contact us directly or comment at our project homepage.
- [ ] Your issue is not a duplicate of an existing issue. If there is an open issue of the same topic, please just comment under it.
- [ ] If you are reporting a bug, please make sure it can be reproduced in the latest release or master branch. Also, please specify detailed procedures to reproduce the bug (screenshots would be greatly appreciated).
- [ ] You have filled out your system environment info.

### Environment Info
Please fill out the following:
1. Operating System (Windows/macOS/Linux):
2. Chrome Version (You can check this under [Menu/Help/About]):
3. Extension Version:

You can see this on extension options page. You can also put the latest commit ID here if you are reporting about the master branch. 

### Steps to Reproduce / Attempted solution
Please be specific here, thanks :)

**Comment by jjj201200** [comment]
请更具模板填写一下基本信息，然后确认是否更新到了最新版本。
目前暂未证实该功能失效了。

**Comment by FUSIZHE** [comment]
问题已解决，谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"DrowsyFlesh"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月20日(星期四) 凌晨2:04
收件人:&nbsp;"bilibili-helper/bilibili-helper"<bilibili-helper@noreply.github.com&gt;;
抄送:&nbsp;"(#_#)"<2026521365@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bilibili-helper/bilibili-helper] 直播间银瓜子自动领取失效（需要验证码） (#664)




请更具模板填写一下基本信息，然后确认是否更新到了最新版本。
 目前暂未证实该功能失效了。

**Comment by jjj201200** [comment]
怎么解决的？

**Comment by FUSIZHE** [comment]
禁用掉了几个其他的插件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"DrowsyFlesh"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月20日(星期四) 晚上11:07
收件人:&nbsp;"bilibili-helper/bilibili-helper"<bilibili-helper@noreply.github.com&gt;;
抄送:&nbsp;"(#_#)"<2026521365@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bilibili-helper/bilibili-helper] #在某些情况下直播间银瓜子自动领取失效（验证码无法自动填写）（之后暂未再次出现） (#664)




怎么解决的？

**Comment by jjj201200** [comment]
方便具体说一下是哪款插件吗？我好方便给其他相似问题的用户一些指导建议，感谢

**Comment by FUSIZHE** [comment]
也可能是插件太多电脑处理不过来导致插件未正常启动




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"DrowsyFlesh"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月21日(星期五) 晚上8:15
收件人:&nbsp;"bilibili-helper/bilibili-helper"<bilibili-helper@noreply.github.com&gt;;
抄送:&nbsp;"(#_#)"<2026521365@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bilibili-helper/bilibili-helper] #在某些情况下直播间银瓜子自动领取失效（验证码无法自动填写）（之后暂未再次出现） (#664)




方便具体说一下是哪款插件吗？我好方便给其他相似问题的用户一些指导建议，感谢

**Comment by FUSIZHE** [comment]
其实我也记不清了，好像是嗅探类或倍速播放类的插件，可能是功能冲突




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"DrowsyFlesh"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月21日(星期五) 晚上8:15
收件人:&nbsp;"bilibili-helper/bilibili-helper"<bilibili-helper@noreply.github.com&gt;;
抄送:&nbsp;"(#_#)"<2026521365@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bilibili-helper/bilibili-helper] #在某些情况下直播间银瓜子自动领取失效（验证码无法自动填写）（之后暂未再次出现） (#664)




方便具体说一下是哪款插件吗？我好方便给其他相似问题的用户一些指导建议，感谢
