### ISSUE TITLE
[Feature Request] 同一视频下同一人弹幕搜索或列出功能

### ISSUE THREAD

**Issue by gaieepo** [bilibili-helper/bilibili-helper#667]
# 起因
时常在视频下想看到某些观者的前后反应的弹幕或前后讨论的会话，然而只能找到此人本身，目前用屏蔽加灰前后目测翻找来代替。而已有搜索助能只对文本进行搜索（适用最新版本）。

## 功能描述
可以进行弹幕点击次级选项按钮、或用户名逆搜索、或同一人弹幕加高亮等形式，帮助和简化这类操作。

## 其它
若已有功能而我不自知，或有不实现的考量，或已有相关讨论，请指引谢谢！

**Comment by xmcp** [comment]
![image](https://user-images.githubusercontent.com/6646473/75745811-5f413880-5d53-11ea-8285-5e802de38ed9.png)

**Comment by gaieepo** [comment]
> ![image](https://user-images.githubusercontent.com/6646473/75745811-5f413880-5d53-11ea-8285-5e802de38ed9.png)

谢谢！

**Comment by jjj201200** [comment]
补充一下，弹幕发送者查询功能中，点击「已经查询的那一行」也会列出该弹幕池中该发送者发送的其他弹幕

**Comment by gaieepo** [comment]
> 补充一下，弹幕发送者查询功能中，点击「已经查询的那一行」也会列出该弹幕池中该发送者发送的其他弹幕

谢告知
