### ISSUE TITLE
bilibili没有广告....

### ISSUE THREAD

**Issue by Open-Super** [bilibili-helper/bilibili-helper#669]
哔哩哔哩没有广告

**Comment by jjj201200** [comment]
嗯？你好呀，你想表达什么呀？

**Comment by Open-Super** [comment]
> 嗯？你好呀，你想表达什么呀？

BILIBILI没有广告啊(视频播放)awa

**Comment by jjj201200** [comment]
@Open-Super b站的视频确实几乎都没有广告哦。

这里是哔哩哔哩助手这款软件的开源项目，并非官方的软件，如果同学你有什么关于这款软件的想法或者反馈的话，欢迎通过提交issue的形式告诉我们哦。

但是如果不是和这些相关的话题和内容的话，我会毫不留情的关闭掉哦。

**Comment by xmcp** [comment]
![image](https://user-images.githubusercontent.com/6646473/76104663-bc1c4780-600e-11ea-972d-5ac9fd6f570f.png)
我猜他的意思是这个
