### ISSUE TITLE
小错别字

### ISSUE THREAD

**Issue by Coolkkmeat** [bilibili-helper/bilibili-helper#672]
![TIM截图20200318001525](https://user-images.githubusercontent.com/36995273/76877002-bb58a080-68ad-11ea-9f00-68b9afff4e9d.jpg)
卡住-卡主

**Comment by jjj201200** [comment]
啊测试版中已经改掉了哈哈，感谢反馈~

**Comment by Coolkkmeat** [comment]
感谢作者的插件，很好用~
