### ISSUE TITLE
网址匹配不了了

### ISSUE THREAD

**Issue by SplitGemini** [bilibili-helper/bilibili-helper#676]
## 问题反馈
哔哩哔哩原视频网址前缀由av改成BV了

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):Windows 10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Chrome 80.0.3987.149 64bits
3. 扩展版本:1.2.15

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
![image](https://user-images.githubusercontent.com/34861918/77287911-a64a9a00-6d11-11ea-9e0e-88a877a5e8ce.png)

**Comment by JasonKhew96** [comment]
【升级公告】AV号全面升级至BV号
https://www.bilibili.com/read/cv5167957

![image](https://user-images.githubusercontent.com/29531167/77290850-07756c00-6d18-11ea-8968-acaa816a6c9c.png)

哎，支持两个呗

**Comment by jjj201200** [comment]
感谢反馈，已经发布测试版本在qq群（548321019）里，可以去下载一下解决暂时的问题

**Comment by sino1641** [comment]
> 感谢反馈，已经发布测试版本在qq群（548321019）里，可以去下载一下解决暂时的问题
> 
> 预计今晚上线

希望保留对av网址的适配，感谢
