### ISSUE TITLE
1.2.15版本问题，功能今天突然失效了（2020.3.23）

### ISSUE THREAD

**Issue by debugbb** [bilibili-helper/bilibili-helper#677]
### 环境信息
请填写以下信息:
1. 操作系统:Windows
2. 浏览器版本:80.0.3987.149
3. 扩展版本:1.2.15
### 重现步骤/尝试的解决方案
视频下载，默认关闭弹幕，深色模式，均失效
已尝试卸载重新安装

**Comment by zhz1237ok** [comment]
刷新了下页面狗眼被闪瞎了，不过也好，换成这种编码方式能容纳更多的视频了，B站居然视频量也破亿了，感叹

**Comment by debugbb** [comment]
> 刷新了下页面狗眼被闪瞎了，不过也好，换成这种编码方式能容纳更多的视频了，B站居然视频量也破亿了，感叹

啊？啥意思？

**Comment by zhz1237ok** [comment]
> > 刷新了下页面狗眼被闪瞎了，不过也好，换成这种编码方式能容纳更多的视频了，B站居然视频量也破亿了，感叹
> 
> 啊？啥意思？

av号现在慢慢过渡到BV号，加入了字母，也就是说，新版的编码能容纳34^10个视频编号，按以前的av号来看要变成很长一串数字

**Comment by jjj201200** [comment]
#676 感谢反馈，问题已重复，请前往该问题

**Comment by debugbb** [comment]
> #676 感谢反馈，问题已重复，请前往该问题

怎么close了，我反馈的是功能失效问题啊？

**Comment by Coolkkmeat** [comment]
> > #676 感谢反馈，问题已重复，请前往该问题
> 
> 怎么close了，我反馈的是功能失效问题啊？

可能这些都是要依靠识别前面的那个号码，现在改成BV了，需要适配新版。

**Comment by jjj201200** [comment]
@debugbb 你反馈的问题和我上面指定的issue是同一个问题，故我关掉了，还望理解

**Comment by debugbb** [comment]
> @debugbb 你反馈的问题和我上面指定的issue是同一个问题，故我关掉了，还望理解
好的，谢谢。我以为你是回答的他呢。
