### ISSUE TITLE
功能请求：添加“诊断链接”

### ISSUE THREAD

**Issue by wordlesswind** [bilibili-helper/bilibili-helper#689]
```
https://www.bilibili.com/blackboard/video-diagnostics.html?bvid=<BVID>&cid=<CID>
https://www.bilibili.com/blackboard/diagnostics.html
```
方便用户诊断播放问题

**Comment by jjj201200** [comment]
emmm加在哪里呢？其实应该没太多人用这个吧？这几个问题需要解决一下

**Comment by wordlesswind** [comment]
> emmm加在哪里呢？其实应该没太多人用这个吧？这几个问题需要解决一下

我也在想，如果没有多少人用的话，在助手的面版上加一个按钮就好了。

没有多少人用的问题还是B站的锅，这种东西藏着掖着。

**Comment by jjj201200** [comment]
按我的理解，这种需求的定位就应该是尽量不需要使用到才对，所以没有必要加到助手里，根本不需要藏着掖着。有问题问客服即可。更加不会加到助手的面板里了哦
