### ISSUE TITLE
在下载视频时没法调整下载清晰度

### ISSUE THREAD

**Issue by zhchw2233** [bilibili-helper/bilibili-helper#692]
请保留一种您需要的语言版本的报告模板
please leave only one kind of these template

## 问题反馈
在您提交问题前, 请检查以下项目:
- [ ] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [ ] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [ ] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [ ] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):
3. 扩展版本:

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)

## Feedback
Before submitting your issue, please check to make sure of the following:
- [ ] You are reporting a bug or making a feature request. If you are looking for general support, please contact us directly or comment at our project homepage.
- [ ] Your issue is not a duplicate of an existing issue. If there is an open issue of the same topic, please just comment under it.
- [ ] If you are reporting a bug, please make sure it can be reproduced in the latest release or master branch. Also, please specify detailed procedures to reproduce the bug (screenshots would be greatly appreciated).
- [ ] You have filled out your system environment info.

### Environment Info
Please fill out the following:
1. Operating System (Windows/macOS/Linux):
2. Chrome Version (You can check this under [Menu/Help/About]):
3. Extension Version:

You can see this on extension options page. You can also put the latest commit ID here if you are reporting about the master branch. 

### Steps to Reproduce / Attempted solution
Please be specific here, thanks :)

**Comment by jjj201200** [comment]
请根据模板填写
另外，为什么下载时可以调整下载清晰度？

**Comment by zhchw2233** [comment]
抱歉，我打扰了您，因为刚开始用这个插件，所以不怎么了解使用方式，所以请您当没有看见吧，对不起打扰到了您。我因为不懂这个网站是什么样的网站所以才发的这个，打扰到了您的时间，如果能请删掉这个这个因为我不了解这个网站而发的这个东西

DrowsyFlesh <notifications@github.com> 于2020年4月6日周一 下午5:13写道：

**Comment by jjj201200** [comment]
@zhchw2233 emmm无妨无妨，如果我想的没错的话，你是希望选择不同清晰度进行下载，如果是的话，你可以通过在视频播放器切换视频清晰度，下载区的下载链接会自动变化。

**Comment by zhchw2233** [comment]
谢谢您，但也打扰到了您，希望我没有打扰到您做重要的事

DrowsyFlesh <notifications@github.com> 于2020年4月9日周四 上午1:05写道：
