### ISSUE TITLE
Edge商店已上架哔哩哔哩助手，需要修复一下

### ISSUE THREAD

**Issue by PanXinYi** [bilibili-helper/bilibili-helper#694]
成功安装助手后点击设置页空白，需要修复一下，之前的google商店的助手就能用，Edge商店的助手就有问题了。

**Comment by jjj201200** [comment]
很疑惑，那不是我们上架的，根据署名，那貌似是edge学360那样自己从chrome同步过去的，我已经重新提交审核。不知道他们会怎么做

**Comment by xmcp** [comment]
该扩展是恶意软件，详细分析见 #695。出于安全考虑，建议立刻卸载该版本。

**Comment by PanXinYi** [comment]
已卸载这个Edge商店的恶意垃圾扩展，请求作者尽快让Edge商店下架第三方拓展，即使不上架也不能用哔哩哔哩助手的名称去坑用户！

**Comment by jjj201200** [comment]
@PanXinYi 已经提交处理了，你说得对，这当然不能啊。。这并不是我们做的呀

**Comment by jjj201200** [comment]
edge已经上架了
https://microsoftedge.microsoft.com/addons/detail/fcfebhekhbkhjjimonjmbgmkbclheaoh?hl=zh-CN
但是盗版仍旧没有被处理，可能因为新冠？暂时不知道
