### ISSUE TITLE
请问有没有大佬提供一下用该插件下载视频的图文教程

### ISSUE THREAD

**Issue by DarthMikuH** [bilibili-helper/bilibili-helper#696]
备注：我的B站在Chromium上
             插件在Chrome上

**Comment by DarthMikuH** [comment]
电脑系统：MAC OS Catalina 10.15.4

**Comment by jjj201200** [comment]
没有也不需要图文教程哦，你只要能看懂我以下所说就可以成功下来了
1. 正确安装并确认已经是最新版本，目前chrome上是1.2.16，edge上是1.2.17.2/3
2. 打开b站的视频播放页面，找到窗口右侧的「助手」字样的粉色按钮，然后点击按钮弹出功能窗口
3. 切换视频到你想到下载的清晰度，然后再点击刚才弹窗中的视频清晰度按钮
4. 等待浏览器下载完成。

** 如果出现合并下载按钮，有时候可能会卡主，这时候只能选择分段下载然后用户自己使用剪辑软件拼接

**Comment by DarthMikuH** [comment]
请问是要用该插件打开主站吗



---原始邮件---
发件人: "DrowsyFlesh"<notifications@github.com&gt;
发送时间: 2020年4月18日(周六) 晚上11:22
收件人: "bilibili-helper/bilibili-helper"<bilibili-helper@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"DarthMikuH"<darthmiku@foxmail.com&gt;;
主题: Re: [bilibili-helper/bilibili-helper] 请问有没有大佬提供一下用该插件下载视频的图文教程 (#696)




 
没有也不需要图文教程哦，你只要能看懂我以下所说就可以成功下来了
  
正确安装并确认已经是最新版本，目前chrome上是1.2.16，edge上是1.2.17.2/3 

打开b站的视频播放页面，找到窗口右侧的「助手」字样的粉色按钮，然后点击按钮弹出功能窗口 

切换视频到你想到下载的清晰度，然后再点击刚才弹窗中的视频清晰度按钮 

等待浏览器下载完成。 
 
** 如果出现合并下载按钮，有时候可能会卡主，这时候只能选择分段下载然后用户自己使用剪辑软件拼接

**Comment by jjj201200** [comment]
@DarthMikuH 没有要求

**Comment by DarthMikuH** [comment]
好的，谢谢



---原始邮件---
发件人: "DrowsyFlesh"<notifications@github.com&gt;
发送时间: 2020年4月18日(周六) 晚上11:37
收件人: "bilibili-helper/bilibili-helper"<bilibili-helper@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"DarthMikuH"<darthmiku@foxmail.com&gt;;
主题: Re: [bilibili-helper/bilibili-helper] 请问有没有大佬提供一下用该插件下载视频的图文教程 (#696)




 
@DarthMikuH 没有要求
